# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfswitch" do
  version "1.19.0"

  on_macos do
    on_intel do
      sha256 "e9d21deaece69523c84a810e783f2ef0b67dc0d4a45e9663bddbc7339cf1e9f3"
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v#{version}/terraform-switcher_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e84e1cb04f995cf286d46b2a5488fb7cb6acdc29b8942178c0816dcc605bd2e3"
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v#{version}/terraform-switcher_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f1502b83f35ddce7f5bb25a2a2ca3fa4c56930e5f8f7a423cea0bdef384fb61b"
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v#{version}/terraform-switcher_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "94168e9bf1a0eff15038058f73494f7d30e12432c1cab6b40b3fcd2f38dfc157"
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v#{version}/terraform-switcher_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "tfswitch"
  desc "The tfswitch command lets you switch between terraform versions."
  homepage "https://warrensbox.github.io/terraform-switcher"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "terraform",
    ]

  binary "tfswitch"
  bash_completion "completions/tfswitch.bash"
  fish_completion "completions/tfswitch.fish"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfswitch"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Type 'tfswitch' on your command line and choose Terraform version that you want from the dropdown
  EOS
end
