# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfswitch" do
  version "1.17.0"

  on_macos do
    on_intel do
      sha256 "0132b04b1063d936a799eb7be82c26ab47e3e278ddb4b5030362238324907879"
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v#{version}/terraform-switcher_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "290f4252ef05d002723f13878ef0dd39c9a78dccb4df20a34c8263f945335288"
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v#{version}/terraform-switcher_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4e90ca05be69f5f13a6a367a39d2fdaaa40cd35a0b540077ab266532c594e532"
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v#{version}/terraform-switcher_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3e9f3d1cef0233d5b8a73740e699c2b723e139ee173abd710eea343e806d96a4"
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v#{version}/terraform-switcher_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "tfswitch"
  desc "The tfswitch command lets you switch between terraform versions."
  homepage "https://warrensbox.github.io/terraform-switcher"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "terraform",
    ]

  binary "tfswitch"
  bash_completion "completions/tfswitch.bash"
  fish_completion "completions/tfswitch.fish"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfswitch"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Type 'tfswitch' on your command line and choose Terraform version that you want from the dropdown
  EOS
end
