# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfswitch" do
  version "1.20.0"

  on_macos do
    on_arm do
      sha256 "20c69987dd2aa7d201d54af4a8eb2526074cc2873ed96fdacf1b01431b5e3da0"
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v#{version}/terraform-switcher_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5d6574d97e00c68875ab302640b6517724e43043ea8fefe1120f45f72f314be7"
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v#{version}/terraform-switcher_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6343ad29a08e8cc3ca1d6fea8f102645cf58540ed3b0953cfe032328c2bc44ca"
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v#{version}/terraform-switcher_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a15b3d5201dfb0f1e17f3346297c0f594ba66240d245367520d1ca70164dda12"
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v#{version}/terraform-switcher_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "tfswitch"
  desc "The tfswitch command lets you switch between terraform versions."
  homepage "https://warrensbox.github.io/terraform-switcher"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "terraform",
    ]

  binary "tfswitch"
  bash_completion "completions/tfswitch.bash"
  fish_completion "completions/tfswitch.fish"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/tfswitch"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Type 'tfswitch' on your command line and choose Terraform version that you want from the dropdown
  EOS
end
