# This file was generated by GoReleaser. DO NOT EDIT.
class HealthCheck < Formula
  desc "The `health-check` command line tool concurrently checks all target groups's health status"
  homepage "https://warrensbox.github.io/health-check"
  version "0.1.96"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/warrensbox/health-check/releases/download/0.1.96/health-check_0.1.96_darwin_amd64.tar.gz"
    sha256 "dac7f9f26502a57e083eb938f0056a6fca9528121ff3a3032693c18f94c31cac"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/warrensbox/health-check/releases/download/0.1.96/health-check_0.1.96_linux_amd64.tar.gz"
      sha256 "8838d537857146b6514dcf497f66739e9d603c78bd0b5586c4a0a4f3058bea30"
    end
  end

  def install
    bin.install "health-check"
  end

  def caveats; <<~EOS
    The `health-check` command line tool concurrently checks all target groups's health status
  EOS
  end

  test do
    system "#{bin}/health-check --version"
  end
end
