# This file was generated by GoReleaser. DO NOT EDIT.
class HealthCheck < Formula
  desc "The `health-check` command line tool concurrently checks all target groups's health status"
  homepage "https://warrensbox.github.io/health-check"
  version "0.1.114"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/warrensbox/health-check/releases/download/0.1.114/health-check_0.1.114_darwin_amd64.tar.gz"
    sha256 "39022d838f31ec1ce91592c01d1b7b20ef6e3f92ea965aebef891e456afc87b1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/warrensbox/health-check/releases/download/0.1.114/health-check_0.1.114_linux_amd64.tar.gz"
      sha256 "5c9c6e14e5bc56f7509eda902f4b2a0144aa77c5d0c7dde6e42c0ceaaa3fced9"
    end
  end

  def install
    bin.install "health-check"
  end

  def caveats; <<~EOS
    The `health-check` command line tool concurrently checks all target groups's health status
  EOS
  end

  test do
    system "#{bin}/health-check --version"
  end
end
