# This file was generated by GoReleaser. DO NOT EDIT.
class Jscheck < Formula
  desc "Recursively lint checks json files in you current directory and subdirectories."
  homepage "https://github.com/warrensbox/jscheck"
  version "0.1.80"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/warrensbox/jscheck/releases/download/0.1.80/jscheck_0.1.80_darwin_x86_64.tar.gz"
    sha256 "42e2b9cdf778af75d3b7cbbb354853d883935826a885e790f3a71b15d895b8e9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/warrensbox/jscheck/releases/download/0.1.80/jscheck_0.1.80_linux_x86_64.tar.gz"
      sha256 "4f2a4f0c6c6d9ad7a9d47799acc1d7497c60d51f9369f2d3d5d60ee66afca8a0"
    end
  end

  def install
    bin.install "jscheck"
  end

  def caveats; <<~EOS
    Type 'jscheck' on your command line and recursively lint checks json files in you current and subdirectories. This command currently only works on MacOs and Linux
  EOS
  end

  test do
    system "#{bin}/jscheck --version"
  end
end
