# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfswitch < Formula
  desc "The tfswitch command lets you switch between terraform versions."
  homepage "https://warrensbox.github.io/terraform-switcher"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v1.1.1/terraform-switcher_v1.1.1_darwin_amd64.tar.gz"
      sha256 "a7cff7df23042121fabddc68e390f7927a18b82d3307d00511b1017e8a7a1c87"

      def install
        bin.install "tfswitch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v1.1.1/terraform-switcher_v1.1.1_darwin_arm64.tar.gz"
      sha256 "500f23e8076a3a039b9500921f75c4a4babbd317895022f22cf538ef937c7986"

      def install
        bin.install "tfswitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v1.1.1/terraform-switcher_v1.1.1_linux_amd64.tar.gz"
      sha256 "cd085a6eeab04a2e555da449ea37bf619116819df9a5151f7f8d0eb85e3f36d1"

      def install
        bin.install "tfswitch"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v1.1.1/terraform-switcher_v1.1.1_linux_armv6.tar.gz"
      sha256 "50ed5a2231855a995e85250331189c60f13cc9af63db57d0facc269ad7b7a394"

      def install
        bin.install "tfswitch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v1.1.1/terraform-switcher_v1.1.1_linux_arm64.tar.gz"
      sha256 "26fcd6673ebd5e380f031fd77f68b7897e32bf02fa56ddcdf4e5e1ebfa78d447"

      def install
        bin.install "tfswitch"
      end
    end
  end

  conflicts_with "terraform"

  def caveats
    <<~EOS
      Type 'tfswitch' on your command line and choose the terraform version that you want from the dropdown. This command currently only works on macOS and Linux
    EOS
  end

  test do
    system "#{bin}/tfswitch --version"
  end
end
