# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfswitch < Formula
  desc "The tfswitch command lets you switch between terraform versions."
  homepage "https://warrensbox.github.io/terraform-switcher"
  version "1.14.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v1.14.0/terraform-switcher_v1.14.0_darwin_amd64.tar.gz"
      sha256 "cebfd93bcecebc6cab180bfa0a81564b3d692efe7f9692fc970b4938853e1e17"

      define_method(:install) do
        bin.install "tfswitch"
        bash_completion.install "tfswitch-completion.bash" => "tfswitch"
        fish_completion.install "tfswitch-completion.fish" => "tfswitch.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v1.14.0/terraform-switcher_v1.14.0_darwin_arm64.tar.gz"
      sha256 "ec376c67039e6f55188be1f08550aba2408aba502ad8975e2cf09bdbcc337d10"

      define_method(:install) do
        bin.install "tfswitch"
        bash_completion.install "tfswitch-completion.bash" => "tfswitch"
        fish_completion.install "tfswitch-completion.fish" => "tfswitch.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v1.14.0/terraform-switcher_v1.14.0_linux_amd64.tar.gz"
      sha256 "83def7f6adfb5147562ae9c7161561e83ad946f94afdba11ab0c6c7cf15ea7ba"
      define_method(:install) do
        bin.install "tfswitch"
        bash_completion.install "tfswitch-completion.bash" => "tfswitch"
        fish_completion.install "tfswitch-completion.fish" => "tfswitch.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v1.14.0/terraform-switcher_v1.14.0_linux_armv6.tar.gz"
      sha256 "5537ead5b27586319596667ad31627ce55921ce05ee2f2f3cf9c4893ac24bb77"
      define_method(:install) do
        bin.install "tfswitch"
        bash_completion.install "tfswitch-completion.bash" => "tfswitch"
        fish_completion.install "tfswitch-completion.fish" => "tfswitch.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/warrensbox/terraform-switcher/releases/download/v1.14.0/terraform-switcher_v1.14.0_linux_arm64.tar.gz"
      sha256 "80d8bc3d4196027758c14321c754383edb41a493fa5c66fbda7d9164b415d8c3"
      define_method(:install) do
        bin.install "tfswitch"
        bash_completion.install "tfswitch-completion.bash" => "tfswitch"
        fish_completion.install "tfswitch-completion.fish" => "tfswitch.fish"
      end
    end
  end

  conflicts_with "terraform"

  def caveats
    <<~EOS
      Type 'tfswitch' on your command line and choose Terraform version that you want from the dropdown
    EOS
  end

  test do
    system "#{bin}/tfswitch --version"
  end
end
