# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgswitch < Formula
  desc "The tgswitch command lets you switch between terragrunt versions."
  homepage "https://warrensbox.github.io/tgswitch"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/warrensbox/tgswitch/releases/download/0.6.0/tgswitch_0.6.0_darwin_arm64.tar.gz"
      sha256 "d6f2425bf515880d4516c1fe4d979f5c0122796587412c08fd5e17a39caba7f3"

      def install
        bin.install "tgswitch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/warrensbox/tgswitch/releases/download/0.6.0/tgswitch_0.6.0_darwin_amd64.tar.gz"
      sha256 "431d912203caecf8e4a73f78f2be8f36dc2247c4b6ae693f9490f99f0e585851"

      def install
        bin.install "tgswitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/warrensbox/tgswitch/releases/download/0.6.0/tgswitch_0.6.0_linux_arm64.tar.gz"
      sha256 "808691afcbee1e667f1969c0cc3f220461d57ecfb074d3e0b61d4367dda08d66"

      def install
        bin.install "tgswitch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/warrensbox/tgswitch/releases/download/0.6.0/tgswitch_0.6.0_linux_amd64.tar.gz"
      sha256 "d1513d77b64645b864b04431dc093c651f7a6bb97ef24037a7d75e90dea1601b"

      def install
        bin.install "tgswitch"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/warrensbox/tgswitch/releases/download/0.6.0/tgswitch_0.6.0_linux_armv6.tar.gz"
      sha256 "238801ed36c1d899db6ed711011bb87a7763d07bcd76ddfa1027db85a821cf65"

      def install
        bin.install "tgswitch"
      end
    end
  end

  def caveats; <<~EOS
    Type 'tgswitch' on your command line and choose the terragrunt version that you want from the dropdown. This command currently only works on MacOs and Linux
  EOS
  end

  test do
    system "#{bin}/tgswitch --version"
  end
end
